let abc=new Date();
console.log(abc.toString());
console.log(abc.toDateString());
console.log(abc.toLocaleString());

// let bc=new Date(2023,8,28,5,3,45);
// console.log(bc.toString());
// console.log(bc.toDateString());
// console.log(bc.toLocaleString());

// let dd1=new Date("16-12-2023")  // invalid as dd-mm-yyyy not allowed
// let dd=new Date("12-17-2023")
// console.log(dd.toString());
// console.log(dd.toDateString());
// console.log(dd.toLocaleString());

// let dd2=new Date("2023-12-10")
// console.log(dd2.toString());
// console.log(dd2.toDateString());
// console.log(dd2.toLocaleString());

// let ee=Date.now();
// console.log(ee);        //in ms
// console.log(Math.round(ee/1000));  //in sec


// let dd=new Date("10-17-2023")
// console.log(dd.getTime());
// console.log(dd);
// console.log(dd.getMonth() + 1);
// console.log(dd.getDay());

// let newDate = new Date()
// console.log(newDate);
// console.log(newDate.getMonth() + 1);
// console.log(newDate.getDay());
